export enum EKeys {
    TYPE = '_type_',
    LENGTH = '_length_',
    FIELD_TYPE = '_fieldType_',
    VALUES = '_values_',
}

export enum EType {
    BOOLEAN = 'boolean',
    DATE = 'date',
    DATE_TIME = 'dateTime',
    TIME = 'time',
    EMAIL = 'email',
    ID = 'id',
    IP = 'ip',
    NULL = 'null',
    UNDEFINED = 'undefined',
    NUMBER = 'number',
    REGEX ='regex',
    WORD ='word',
    SENTENCE = 'sentence',
    URL = 'url',
    OBJECT = 'object',
    ARRAY = 'array',
    CUSTOM = 'custom',
    ZIP_CODE = 'zipCode',
    COUNTRY = 'country',
    CITY = 'city',
    CURRENCY = 'currency',
    COUNTRY_CODE = 'countryCode',
    CARD_NUMBER = 'cardNumber',
    CREDIT_CARD = 'creditCard',
    PERSON = 'person',
}