import { colorFormat, zipCodeFormat } from '../interfaces';

export const DEFAULT_ARRAY_LENGTH: number = 10;
export const GAP_YEARS: number = 20;
export const FORMAT_DATE: string = 'dd/MM/yyyy';
export const FORMAT_DATE_TIME: string = 'yyyy-MM-dd\'T\'HH:mm:ss.SSSXXX';
export const FORMAT_TIME: string = 'HH:mm:ss';
export const MINIMUM_NUMBER: number = -10000;
export const MAXIMUM_NUMBER: number = 10000;
export const MINIMUM_WORD: number = 10;
export const MAXIMUM_WORD: number = 30;
export const DEFAULT_ZIP_CODE_FORMAT: zipCodeFormat = 'any';
export const DEFAULT_COLOR_FORMAT: colorFormat = 'name';
export const REGEX_VENDORS = {
    masterCard: '^5[1-5][0-9]{14}$',
    visa: '^4[0-9]{12}(?:[0-9]{3})?$',
    americanExpress: '^3[47][0-9]{13}$',
    discoverCard: '^6(?:011|5[0-9]{2})[0-9]{12}$'
};
export const FIRST_NAMES = [ 'John', 'Jane', 'Michael', 'Emily', 'David', 'Sarah', 'Daniel', 'Olivia', 'James', 'Emma',
    'Ava', 'Matthew', 'William', 'Sophia', 'Joseph', 'Isabella', 'Benjamin', 'Mia', 'Jacob', 'Charlotte', 'Samuel', 'Amelia',
    'Henry', 'Evelyn', 'Lucas', 'Mohammed', 'Jackson', 'Ali', 'Sebastian', 'Jayden', 'Elizabeth', 'Ethan', 'Mila', 'Alexander',
    'Ella', 'Joshua', 'Grace', 'Aria', 'Julian', 'Chloe', 'Vincent', 'Aubrey', 'Dylan', 'Zoe', 'Grayson', 'Levi', 'Isaac',
    'Hannah', 'Julia', 'Nathan', 'Lily', 'Theodore', 'Amelia', 'Caleb', 'Mason', 'Eli', 'Adam', 'Aiden', 'Ryan', 'Carter',
    'Wyatt', 'Ezra', 'Natalie', 'Jaxon', 'Hudson', 'Luke', 'Landon', 'Nolan', 'Aaron', 'Cameron'
];
export const LAST_NAMES = [ 'Smith', 'Johnson', 'Williams', 'Brown', 'Taylor', 'Anderson', 'Jones', 'Miller', 'Davis',
    'Garcia', 'Rodriguez', 'Martinez', 'Hernandez', 'Lopez', 'Gonzalez', 'Wilson', 'Anderson', 'Thomas', 'Lee', 'Walker',
    'Hall', 'Allen', 'Young', 'Harris', 'King', 'Wright', 'Hill', 'Scott', 'Green', 'Adams', 'Baker', 'Nelson', 'Carter',
    'Mitchell', 'Perez', 'Roberts', 'Turner', 'Phillips', 'Campbell', 'Parker', 'Evans', 'Edwards', 'Collins', 'Stewart',
    'Sanchez', 'Morris', 'Rogers', 'Reed', 'Cook', 'Morgan', 'Bell', 'Murphy', 'Bailey', 'Rivera', 'Cooper', 'Richardson',
];
export const PROTOCOLS = [ 'http', 'https', 'ftp', 'ftps' ];
export const EMAIL_DOMAINS = [ 'gmail.com', 'gmail.ca', 'yandex.com.ua', 'yandex.com.by', 'yandex.com.kz', 'hotmail.com',
    'yahoo.it', 'yahoo.com', 'icloud.com', 'yandex.by', 'yandex.kz', 'live.com', 'msn.com', 'gmail.de', 'outlook.com',
    'mail.com', 'yahoo.fr', 'inbox.com', 'aol.com', 'zoho.com', 'yahoo.de', 'protonmail.com', 'yandex.ru', 'yandex.com',
    'yandex.ua', 'yandex.com.tr'
];
export const DOMAINS = [ 'google.com', 'facebook.com', 'twitter.com', 'amazon.com', 'youtube.com', 'reddit.com', 'linkedin.com', 'ebay.com',
    'wikipedia.org', 'instagram.com', 'microsoft.com', 'apple.com', 'yahoo.com', 'netflix.com', 'cnn.com', 'wordpress.org', 'adobe.com',
    'github.com', 'nytimes.com', 'stackoverflow.com', 'craigslist.org', 'imdb.com', 'espn.com', 'nasa.gov', 'weather.com', 'pinterest.com',
    'bbc.co.uk', 'nike.com', 'spotify.com', 'nationalgeographic.com', 'forbes.com', 'cnbc.com', 'hulu.com', 'whitehouse.gov', 'npr.org',
    'usnews.com', 'oracle.com', 'nintendo.com', 'cbsnews.com', 'huffpost.com', 'harvard.edu', 'britannica.com' ];

export const STREETS = [ 'Abbey Road', 'Akihabara Electric Town', 'Anna Salai', 'Aspen Street', 'Avenue des Champs-Élysées', 'Avenue Foch',
    'Avenue Montaigne', 'Bay Street', 'Baker Street', 'Berliner Straße', 'Birch Road', 'Bond Street', 'Bourke Street', 'Brigade Road',
    'Boulevard Haussmann', 'Boulevard Saint-Michel', 'Burrard Street', 'Cedar Lane', 'Chestnut Street', 'Chandni Chowk', 'Church Road',
    'Collins Street', 'Cypress Road', 'Dresdner Straße', 'Dotonbori', 'Dundas Street', 'Elm Street', 'Elizabeth Street', 'Flinders Street',
    'Fleet Street', 'Frankfurter Allee', 'Friedrichstraße', 'George Street', 'Ginza', 'Gion', 'Goethestraße', 'Granville Street',
    'Harajuku Takeshita Street', 'Hauptstraße', 'Hickory Court', 'High Street', 'Hill Road', 'Jawaharlal Nehru Road', 'Janpath', 'Juniper Drive',
    'Kaiserstraße', 'King Street', 'King\'s Road', 'Kurfürstendamm', 'La Trobe Street', 'Linking Road', 'Lodi Road', 'Lombard Street',
    'London Road', 'Ludwigstraße', 'Magnolia Street', 'Main Street', 'Maple Drive', 'Marine Drive', 'MG Road', 'Münchner Straße',
    'Nakamise Shopping Street', 'Nihonbashi', 'Oak Avenue', 'Odaiba', 'Omotesando', 'Oxford Street', 'Park Avenue', 'Park Street',
    'Pine Street', 'Pitt Street', 'Place Vendôme', 'Poplar Avenue', 'Portage Avenue', 'Portobello Road', 'Queen Street', 'Redwood Lane',
    'Robson Street', 'Roppongi Hills', 'Rue de la Croix', 'Rue de la Paix', 'Rue de Rivoli', 'Rue des Rosiers', 'Rue du Commerce',
    'Rue du Faubourg Saint-Honoré', 'Rue Saint-Honoré', 'Schlossallee', 'Shibuya Crossing', 'Shinjuku Golden Gai', 'Smith Street',
    'Spencer Street', 'Spruce Avenue', 'St. Catherine Street', 'Station Road', 'Sassafras Drive', 'Savile Row', 'Smith Street', 'Sycamore Lane',
    'Swanston Street', 'Walnut Lane', 'Whyte Avenue', 'Willow Lane', 'Wilhelmstraße', 'Yonge Street'
];

export const COLORS = [ 'Red', 'Orange', 'Yellow', 'Green', 'Blue', 'Indigo', 'Violet', 'Black', 'White', 'Gray', 'Brown', 'Pink', 'Purple',
    'Cyan', 'Magenta', 'Lavender', 'Teal', 'Turquoise', 'Maroon', 'Navy', 'Gold', 'Silver', 'Coral', 'Lime', 'Olive', 'Plum', 'Salmon', 'Slate',
    'Tan', 'Wheat', 'Aquamarine', 'Beige', 'Crimson', 'Ivory', 'Khaki', 'Lemon', 'Mint', 'Periwinkle', 'Rose', 'Saffron', 'Sky', 'Tomato',
    'Amber', 'Bisque', 'Chartreuse', 'Chocolate', 'Fuchsia', 'Lavender', 'Mauve', 'Ochre', 'Peach', 'Pear', 'Ruby', 'Sapphire', 'Tangerine',
    'Topaz', 'Cerulean', 'Denim', 'Emerald', 'Magenta', 'Mulberry', 'Onyx', 'Platinum', 'Rust', 'Sage', 'Sepia', 'Terra', 'Verdigris',
    'Vermilion', 'Viridian', 'Zaffre', 'Alizarin', 'Amaranth', 'Auburn', 'Bittersweet', 'Burgundy', 'Byzantium', 'Carmine', 'Cordovan',
    'Crimson', 'Dandelion', 'Ebony', 'Firebrick', 'Flamingo', 'Gamboge', 'Harlequin', 'Heliotrope', 'Honeydew', 'Isabelline', 'Jade', 'Jonquil',
    'Lilac', 'Marigold', 'Moccasin', 'Mustard', 'Ocean', 'Pansy', 'Papaya', 'Peach', 'Pearly', 'Pine', 'Razzmatazz', 'Robin', 'Sapphire',
    'Seashell', 'Sunset', 'Thistle', 'Tickle', 'Tumbleweed', 'Ultramarine', 'Vanilla', 'Violet', 'Watermelon', 'Wild', 'Zinnwaldite',
    'Amethyst', 'Burgundy', 'Cobalt', 'Cyan', 'Emerald', 'Gold', 'Jade', 'Lilac', 'Magenta', 'Ruby', 'Sapphire', 'Silver', 'Turquoise', 'Violet'
];

export const ANIMALS = [ 'cat', 'dog', 'elephant', 'lion', 'tiger', 'giraffe', 'zebra', 'monkey', 'bear', 'horse', 'penguin', 'koala', 'dolphin',
    'panda', 'cheetah', 'snake', 'crocodile', 'rhinoceros', 'hippopotamus', 'gorilla', 'parrot', 'camel', 'otter', 'rabbit', 'chimpanzee',
    'gazelle', 'seahorse', 'octopus', 'jaguar', 'polar bear', 'flamingo', 'elephant seal', 'zebu', 'scorpion', 'peacock', 'kangaroo', 'wombat',
    'orca', 'quokka', 'platypus', 'lemur', 'alpaca', 'hammerhead shark', 'hedgehog', 'sloth', 'wolf', 'raccoon', 'armadillo', 'chinchilla',
    'goat', 'bison', 'lynx', 'emu', 'puffin', 'walrus', 'beaver', 'meerkat', 'hyena', 'pangolin', 'yak', 'mongoose', 'koala', 'ibex', 'buffalo',
    'lynx', 'porcupine', 'warthog', 'quail', 'elephant bird', 'tapir', 'narwhal', 'cockatoo', 'lemming', 'squirrel', 'rattlesnake', 'panther',
    'wolverine', 'toucan', 'zebadiah', 'cow', 'sheep', 'goose', 'duck', 'pig', 'chicken', 'turkey', 'donkey', 'deer', 'goat', 'rabbit', 'mouse',
    'rat', 'guinea pig', 'hamster', 'ferret', 'llama', 'alpaca', 'yak', 'reindeer', 'buffalo', 'bison', 'moose', 'elk', 'zebu', 'giraffe',
    'hippopotamus', 'pangolin', 'anteater', 'beagle', 'cockroach', 'dalmatian', 'echidna', 'falcon', 'goldfish', 'honey badger', 'iguana',
    'jellyfish', 'koala bear', 'lemur', 'mongoose', 'newt', 'opossum', 'penguin', 'quokka', 'raccoon', 'salamander', 'toucan', 'umbrellabird',
    'vampire bat', 'walrus', 'x-ray tetra', 'yak', 'zebra', 'aardvark', 'butterfly', 'caterpillar', 'dragonfly', 'elephant seal', 'firefly',
    'grasshopper', 'honeybee', 'inchworm', 'jellyfish', 'katydid'
];

export const CURRENCIES = {
    'AFA': '؋',
    'ALL': 'Lek',
    'DZD': 'دج',
    'AOA': 'Kz',
    'ARS': '$',
    'AMD': '֏',
    'AWG': 'ƒ',
    'AUD': '$',
    'AZN': 'm',
    'BSD': 'B$',
    'BHD': '.د.ب',
    'BDT': '৳',
    'BBD': 'Bds$',
    'BYR': 'Br',
    'BEF': 'fr',
    'BZD': '$',
    'BMD': '$',
    'BTN': 'Nu.',
    'BTC': '฿',
    'BOB': 'Bs.',
    'BAM': 'KM',
    'BWP': 'P',
    'BRL': 'R$',
    'GBP': '£',
    'BND': 'B$',
    'BGN': 'Лв.',
    'BIF': 'FBu',
    'KHR': 'KHR',
    'CAD': '$',
    'CVE': '$',
    'KYD': '$',
    'XOF': 'CFA',
    'XAF': 'FCFA',
    'XPF': '₣',
    'CLP': '$',
    'CLF': 'CLF',
    'CNY': '¥',
    'COP': '$',
    'KMF': 'CF',
    'CDF': 'FC',
    'CRC': '₡',
    'HRK': 'kn',
    'CUC': '$, CUC',
    'CZK': 'Kč',
    'DKK': 'Kr.',
    'DJF': 'Fdj',
    'DOP': '$',
    'XCD': '$',
    'EGP': 'ج.م',
    'ERN': 'Nfk',
    'EEK': 'kr',
    'ETB': 'Nkf',
    'EUR': '€',
    'FKP': '£',
    'FJD': 'FJ$',
    'GMD': 'D',
    'GEL': 'ლ',
    'DEM': 'DM',
    'GHS': 'GH₵',
    'GIP': '£',
    'GRD': '₯, Δρχ, Δρ',
    'GTQ': 'Q',
    'GNF': 'FG',
    'GYD': '$',
    'HTG': 'G',
    'HNL': 'L',
    'HKD': '$',
    'HUF': 'Ft',
    'ISK': 'kr',
    'INR': '₹',
    'IDR': 'Rp',
    'IRR': '﷼',
    'IQD': 'د.ع',
    'ILS': '₪',
    'ITL': 'L,£',
    'JMD': 'J$',
    'JPY': '¥',
    'JOD': 'ا.د',
    'KZT': 'лв',
    'KES': 'KSh',
    'KWD': 'ك.د',
    'KGS': 'лв',
    'LAK': '₭',
    'LVL': 'Ls',
    'LBP': '£',
    'LSL': 'L',
    'LRD': '$',
    'LYD': 'د.ل',
    'LTC': 'Ł',
    'LTL': 'Lt',
    'MOP': '$',
    'MKD': 'ден',
    'MGA': 'Ar',
    'MWK': 'MK',
    'MYR': 'RM',
    'MVR': 'Rf',
    'MRO': 'MRU',
    'MUR': '₨',
    'MXN': '$',
    'MDL': 'L',
    'MNT': '₮',
    'MAD': 'MAD',
    'MZM': 'MT',
    'MMK': 'K',
    'NAD': '$',
    'NPR': '₨',
    'ANG': 'ƒ',
    'TWD': '$',
    'NZD': '$',
    'NIO': 'C$',
    'NGN': '₦',
    'KPW': '₩',
    'NOK': 'kr',
    'OMR': '.ع.ر',
    'PKR': '₨',
    'PAB': 'B/.',
    'PGK': 'K',
    'PYG': '₲',
    'PEN': 'S/.',
    'PHP': '₱',
    'PLN': 'zł',
    'QAR': 'ق.ر',
    'RON': 'lei',
    'RUB': '₽',
    'RWF': 'FRw',
    'SVC': '₡',
    'WST': 'SAT',
    'STD': 'Db',
    'SAR': '﷼',
    'RSD': 'din',
    'SCR': 'SRe',
    'SLL': 'Le',
    'SGD': '$',
    'SKK': 'Sk',
    'SBD': 'Si$',
    'SOS': 'Sh.so.',
    'ZAR': 'R',
    'KRW': '₩',
    'SSP': '£',
    'XDR': 'SDR',
    'LKR': 'Rs',
    'SHP': '£',
    'SDG': '.س.ج',
    'SRD': '$',
    'SZL': 'E',
    'SEK': 'kr',
    'CHF': 'CHf',
    'SYP': 'LS',
    'TJS': 'SM',
    'TZS': 'TSh',
    'THB': '฿',
    'TOP': '$',
    'TTD': '$',
    'TND': 'ت.د',
    'TRY': '₺',
    'TMT': 'T',
    'UGX': 'USh',
    'UAH': '₴',
    'AED': 'إ.د',
    'UYU': '$',
    'USD': '$',
    'UZS': 'лв',
    'VUV': 'VT',
    'VEF': 'Bs',
    'VND': '₫',
    'YER': '﷼',
    'ZMK': 'ZK',
    'ZWL': '$'
};

export const CONTINENTS = [ 'Africa', 'Antarctica', 'Asia', 'Australia/Oceania', 'Europe', 'North America', 'South America' ];

export const COUNTRIES = [
    { name: 'Afganistan', code: 'AF', capital: 'Kabul' },
    { name: 'Ahvenanmaa', code: 'AX', capital: 'Mariehamn' },
    { name: 'Albania', code: 'AL', capital: 'Tirana' },
    { name: 'Algeria', code: 'DZ', capital: 'Algiers' },
    { name: 'Amerikan Samoa', code: 'AS', capital: 'Pago Pago' },
    { name: 'Andorra', code: 'AD', capital: 'Andorra la Vella' },
    { name: 'Angola', code: 'AO', capital: 'Luanda' },
    { name: 'Anguilla', code: 'AI', capital: 'The Valley' },
    { name: 'Antarktis', code: 'AQ', capital: 'Antarctica' },
    { name: 'Antigua ja Barbuda', code: 'AG', capital: 'St. John\'s' },
    { name: 'Argentiina', code: 'AR', capital: 'Buenos Aires' },
    { name: 'Armenia', code: 'AM', capital: 'Yerevan' },
    { name: 'Aruba', code: 'AW', capital: 'Oranjestad' },
    { name: 'Australia', code: 'AU', capital: 'Canberra' },
    { name: 'Itävalta', code: 'AT', capital: 'Vienna' },
    { name: 'Azerbaidžan', code: 'AZ', capital: 'Baku' },
    { name: 'Bahama', code: 'BS', capital: 'Nassau' },
    { name: 'Bahrain', code: 'BH', capital: 'Manama' },
    { name: 'Bangladesh', code: 'BD', capital: 'Dhaka' },
    { name: 'Barbados', code: 'BB', capital: 'Bridgetown' },
    { name: 'Valko-Venäjä', code: 'BY', capital: 'Minsk' },
    { name: 'Belgia', code: 'BE', capital: 'Brussels' },
    { name: 'Belize', code: 'BZ', capital: 'Belmopan' },
    { name: 'Benin', code: 'BJ', capital: 'Porto-Novo' },
    { name: 'Bermuda', code: 'BM', capital: 'Hamilton' },
    { name: 'Bhutan', code: 'BT', capital: 'Thimphu' },
    { name: 'Bolivia', code: 'BO', capital: 'Sucre' },
    { name: 'Bonaire, Sint Eustatius ja Saba', code: 'BQ', capital: 'Kralendijk' },
    { name: 'Bosnia ja Hertsegovina', code: 'BA', capital: 'Sarajevo' },
    { name: 'Botswana', code: 'BW', capital: 'Gaborone' },
    { name: 'Bouvetin saari', code: 'BV', capital: '' },
    { name: 'Brasilia', code: 'BR', capital: 'Brasilia' },
    { name: 'Brittiläinen Intian valtameren alue', code: 'IO', capital: 'Diego Garcia' },
    { name: 'Brunei Darussalam', code: 'BN', capital: 'Bandar Seri Begawan' },
    { name: 'Bulgaria', code: 'BG', capital: 'Sofia' },
    { name: 'Burkina Faso', code: 'BF', capital: 'Ouagadougou' },
    { name: 'Burundi', code: 'BI', capital: 'Bujumbura' },
    { name: 'Kambodža', code: 'KH', capital: 'Phnom Penh' },
    { name: 'Kamerun', code: 'CM', capital: 'Yaounde' },
    { name: 'Kanada', code: 'CA', capital: 'Ottawa' },
    { name: 'Kap Verde', code: 'CV', capital: 'Praia' },
    { name: 'Caymansaaret', code: 'KY', capital: 'George Town' },
    { name: 'Keski-Afrikan tasavalta', code: 'CF', capital: 'Bangui' },
    { name: 'Tšad', code: 'TD', capital: 'N\'Djamena' },
    { name: 'Chile', code: 'CL', capital: 'Santiago' },
    { name: 'Kiina', code: 'CN', capital: 'Beijing' },
    { name: 'Joulusaari', code: 'CX', capital: 'Flying Fish Cove' },
    { name: 'Kookossaaret (Keeling)', code: 'CC', capital: 'West Island' },
    { name: 'Kolumbia', code: 'CO', capital: 'Bogota' },
    { name: 'Komorit', code: 'KM', capital: 'Moroni' },
    { name: 'Kongo', code: 'CG', capital: 'Brazzaville' },
    { name: 'Kongo, Kongon demokraattinen tasavalta', code: 'CD', capital: 'Kinshasa' },
    { name: 'Cook saaret', code: 'CK', capital: 'Avarua' },
    { name: 'Costa Rica', code: 'CR', capital: 'San Jose' },
    { name: 'Norsunluurannikko', code: 'CI', capital: 'Yamoussoukro' },
    { name: 'Kroatia', code: 'HR', capital: 'Zagreb' },
    { name: 'Kuuba', code: 'CU', capital: 'Havana' },
    { name: 'Curacao', code: 'CW', capital: 'Willemstad' },
    { name: 'Kypros', code: 'CY', capital: 'Nicosia' },
    { name: 'Tšekin tasavalta', code: 'CZ', capital: 'Prague' },
    { name: 'Tanska', code: 'DK', capital: 'Copenhagen' },
    { name: 'Djibouti', code: 'DJ', capital: 'Djibouti' },
    { name: 'Dominica', code: 'DM', capital: 'Roseau' },
    { name: 'Dominikaaninen tasavalta', code: 'DO', capital: 'Santo Domingo' },
    { name: 'Ecuador', code: 'EC', capital: 'Quito' },
    { name: 'Egypti', code: 'EG', capital: 'Cairo' },
    { name: 'El Salvador', code: 'SV', capital: 'San Salvador' },
    { name: 'Päiväntasaajan Guinea', code: 'GQ', capital: 'Malabo' },
    { name: 'Eritrea', code: 'ER', capital: 'Asmara' },
    { name: 'Viro', code: 'EE', capital: 'Tallinn' },
    { name: 'Etiopia', code: 'ET', capital: 'Addis Ababa' },
    { name: 'Falklandinsaaret (Malvinas)', code: 'FK', capital: 'Stanley' },
    { name: 'Färsaaret', code: 'FO', capital: 'Torshavn' },
    { name: 'Fidži', code: 'FJ', capital: 'Suva' },
    { name: 'Suomi', code: 'FI', capital: 'Helsinki' },
    { name: 'Ranska', code: 'FR', capital: 'Paris' },
    { name: 'Ranskan Guayana', code: 'GF', capital: 'Cayenne' },
    { name: 'Ranskan Polynesia', code: 'PF', capital: 'Papeete' },
    { name: 'Ranskan eteläiset alueet', code: 'TF', capital: 'Port-aux-Francais' },
    { name: 'Gabon', code: 'GA', capital: 'Libreville' },
    { name: 'Gambia', code: 'GM', capital: 'Banjul' },
    { name: 'Georgia', code: 'GE', capital: 'Tbilisi' },
    { name: 'Saksa', code: 'DE', capital: 'Berlin' },
    { name: 'Ghana', code: 'GH', capital: 'Accra' },
    { name: 'Gibraltar', code: 'GI', capital: 'Gibraltar' },
    { name: 'Kreikka', code: 'GR', capital: 'Athens' },
    { name: 'Grönlanti', code: 'GL', capital: 'Nuuk' },
    { name: 'Grenada', code: 'GD', capital: 'St. George\'s' },
    { name: 'Guadeloupe', code: 'GP', capital: 'Basse-Terre' },
    { name: 'Guam', code: 'GU', capital: 'Hagatna' },
    { name: 'Guatemala', code: 'GT', capital: 'Guatemala City' },
    { name: 'Guernsey', code: 'GG', capital: 'St Peter Port' },
    { name: 'Guinea', code: 'GN', capital: 'Conakry' },
    { name: 'Guinea-Bissau', code: 'GW', capital: 'Bissau' },
    { name: 'Guyana', code: 'GY', capital: 'Georgetown' },
    { name: 'Haiti', code: 'HT', capital: 'Port-au-Prince' },
    { name: 'Heardin saari ja McDonaldsaaret', code: 'HM', capital: '' },
    { name: 'Pyhä istuin (Vatikaanin kaupunkivaltio)', code: 'VA', capital: 'Vatican City' },
    { name: 'Honduras', code: 'HN', capital: 'Tegucigalpa' },
    { name: 'Hong Kong', code: 'HK', capital: 'Hong Kong' },
    { name: 'Unkari', code: 'HU', capital: 'Budapest' },
    { name: 'Islanti', code: 'IS', capital: 'Reykjavik' },
    { name: 'Intia', code: 'IN', capital: 'New Delhi' },
    { name: 'Indonesia', code: 'ID', capital: 'Jakarta' },
    { name: 'Iran, Islannin tasavalta', code: 'IR', capital: 'Tehran' },
    { name: 'Irak', code: 'IQ', capital: 'Baghdad' },
    { name: 'Irlanti', code: 'IE', capital: 'Dublin' },
    { name: 'Mansaari', code: 'IM', capital: 'Douglas, Isle of Man' },
    { name: 'Israel', code: 'IL', capital: 'Jerusalem' },
    { name: 'Italia', code: 'IT', capital: 'Rome' },
    { name: 'Jamaika', code: 'JM', capital: 'Kingston' },
    { name: 'Japani', code: 'JP', capital: 'Tokyo' },
    { name: 'Jersey', code: 'JE', capital: 'Saint Helier' },
    { name: 'Jordania', code: 'JO', capital: 'Amman' },
    { name: 'Kazakstan', code: 'KZ', capital: 'Astana' },
    { name: 'Kenia', code: 'KE', capital: 'Nairobi' },
    { name: 'Kiribati', code: 'KI', capital: 'Tarawa' },
    { name: 'Korea, Korean demokraattinen kansantasavalta', code: 'KP', capital: 'Pyongyang' },
    { name: 'Korean tasavalta', code: 'KR', capital: 'Seoul' },
    { name: 'Kosovo', code: 'XK', capital: 'Pristina' },
    { name: 'Kuwait', code: 'KW', capital: 'Kuwait City' },
    { name: 'Kirgisia', code: 'KG', capital: 'Bishkek' },
    { name: 'Laon Kansan Demokraattinen Tasavalta', code: 'LA', capital: 'Vientiane' },
    { name: 'Latvia', code: 'LV', capital: 'Riga' },
    { name: 'Libanon', code: 'LB', capital: 'Beirut' },
    { name: 'Lesotho', code: 'LS', capital: 'Maseru' },
    { name: 'Liberia', code: 'LR', capital: 'Monrovia' },
    { name: 'Libyan arabiemiiri Jamahiriya', code: 'LY', capital: 'Tripolis' },
    { name: 'Liechtenstein', code: 'LI', capital: 'Vaduz' },
    { name: 'Liettua', code: 'LT', capital: 'Vilnius' },
    { name: 'Luxemburg', code: 'LU', capital: 'Luxembourg' },
    { name: 'Macao', code: 'MO', capital: 'Macao' },
    { name: 'Makedonia, entinen Jugoslavian tasavalta Makedonia', code: 'MK', capital: 'Skopje' },
    { name: 'Madagaskar', code: 'MG', capital: 'Antananarivo' },
    { name: 'Malawi', code: 'MW', capital: 'Lilongwe' },
    { name: 'Malesia', code: 'MY', capital: 'Kuala Lumpur' },
    { name: 'Malediivit', code: 'MV', capital: 'Male' },
    { name: 'Mali', code: 'ML', capital: 'Bamako' },
    { name: 'Malta', code: 'MT', capital: 'Valletta' },
    { name: 'Marshallsaaret', code: 'MH', capital: 'Majuro' },
    { name: 'Martinique', code: 'MQ', capital: 'Fort-de-France' },
    { name: 'Mauritania', code: 'MR', capital: 'Nouakchott' },
    { name: 'Mauritius', code: 'MU', capital: 'Port Louis' },
    { name: 'Mayotte', code: 'YT', capital: 'Mamoudzou' },
    { name: 'Meksiko', code: 'MX', capital: 'Mexico City' },
    { name: 'Mikronesia, Liettuan osavaltiot', code: 'FM', capital: 'Palikir' },
    { name: 'Moldovan tasavalta', code: 'MD', capital: 'Chisinau' },
    { name: 'Monaco', code: 'MC', capital: 'Monaco' },
    { name: 'Mongolia', code: 'MN', capital: 'Ulan Bator' },
    { name: 'Montenegro', code: 'ME', capital: 'Podgorica' },
    { name: 'Montserrat', code: 'MS', capital: 'Plymouth' },
    { name: 'Marokko', code: 'MA', capital: 'Rabat' },
    { name: 'Mosambik', code: 'MZ', capital: 'Maputo' },
    { name: 'Myanmar', code: 'MM', capital: 'Nay Pyi Taw' },
    { name: 'Namibia', code: 'NA', capital: 'Windhoek' },
    { name: 'Nauru', code: 'NR', capital: 'Yaren' },
    { name: 'Nepal', code: 'NP', capital: 'Kathmandu' },
    { name: 'Alankomaat', code: 'NL', capital: 'Amsterdam' },
    { name: 'Alankomaiden Antillit', code: 'AN', capital: 'Willemstad' },
    { name: 'Uusi-Caledonia', code: 'NC', capital: 'Noumea' },
    { name: 'Uusi Seelanti', code: 'NZ', capital: 'Wellington' },
    { name: 'Nicaragua', code: 'NI', capital: 'Managua' },
    { name: 'Niger', code: 'NE', capital: 'Niamey' },
    { name: 'Nigeria', code: 'NG', capital: 'Abuja' },
    { name: 'Niue', code: 'NU', capital: 'Alofi' },
    { name: 'Norfolkin saari', code: 'NF', capital: 'Kingston' },
    { name: 'Pohjois-Mariaanit', code: 'MP', capital: 'Saipan' },
    { name: 'Norja', code: 'NO', capital: 'Oslo' },
    { name: 'Oman', code: 'OM', capital: 'Muscat' },
    { name: 'Pakistan', code: 'PK', capital: 'Islamabad' },
    { name: 'Palau', code: 'PW', capital: 'Melekeok' },
    { name: 'Palestiinan alue, miehitetty', code: 'PS', capital: 'East Jerusalem' },
    { name: 'Panama', code: 'PA', capital: 'Panama City' },
    { name: 'Papua-Uusi-Guinea', code: 'PG', capital: 'Port Moresby' },
    { name: 'Paraguay', code: 'PY', capital: 'Asuncion' },
    { name: 'Peru', code: 'PE', capital: 'Lima' },
    { name: 'Filippiinit', code: 'PH', capital: 'Manila' },
    { name: 'Pitcairn', code: 'PN', capital: 'Adamstown' },
    { name: 'Puola', code: 'PL', capital: 'Warsaw' },
    { name: 'Portugali', code: 'PT', capital: 'Lisbon' },
    { name: 'Puerto Rico', code: 'PR', capital: 'San Juan' },
    { name: 'Qatar', code: 'QA', capital: 'Doha' },
    { name: 'Reunion', code: 'RE', capital: 'Saint-Denis' },
    { name: 'Romania', code: 'RO', capital: 'Bucharest' },
    { name: 'Venäjän federaatio', code: 'RU', capital: 'Moscow' },
    { name: 'Ruanda', code: 'RW', capital: 'Kigali' },
    { name: 'Saint Barthelemy', code: 'BL', capital: 'Gustavia' },
    { name: 'Pyhä Helena', code: 'SH', capital: 'Jamestown' },
    { name: 'Saint Kitts ja Nevis', code: 'KN', capital: 'Basseterre' },
    { name: 'Saint Lucia', code: 'LC', capital: 'Castries' },
    { name: 'Saint Martin', code: 'MF', capital: 'Marigot' },
    { name: 'Saint Pierre ja Miquelon', code: 'PM', capital: 'Saint-Pierre' },
    { name: 'Saint Vincent ja Grenadiinit', code: 'VC', capital: 'Kingstown' },
    { name: 'Samoa', code: 'WS', capital: 'Apia' },
    { name: 'San Marino', code: 'SM', capital: 'San Marino' },
    { name: 'Sao Tome ja Principe', code: 'ST', capital: 'Sao Tome' },
    { name: 'Saudi-Arabia', code: 'SA', capital: 'Riyadh' },
    { name: 'Senegal', code: 'SN', capital: 'Dakar' },
    { name: 'Serbia', code: 'RS', capital: 'Belgrade' },
    { name: 'Serbia ja Montenegro', code: 'CS', capital: 'Belgrade' },
    { name: 'Seychellit', code: 'SC', capital: 'Victoria' },
    { name: 'Sierra Leone', code: 'SL', capital: 'Freetown' },
    { name: 'Singapore', code: 'SG', capital: 'Singapur' },
    { name: 'St Martin', code: 'SX', capital: 'Philipsburg' },
    { name: 'Slovakia', code: 'SK', capital: 'Bratislava' },
    { name: 'Slovenia', code: 'SI', capital: 'Ljubljana' },
    { name: 'Solomonsaaret', code: 'SB', capital: 'Honiara' },
    { name: 'Somalia', code: 'SO', capital: 'Mogadishu' },
    { name: 'Etelä-Afrikka', code: 'ZA', capital: 'Pretoria' },
    { name: 'Etelä-Georgia ja Eteläiset Sandwich-saaret', code: 'GS', capital: 'Grytviken' },
    { name: 'eteläsudan', code: 'SS', capital: 'Juba' },
    { name: 'Espanja', code: 'ES', capital: 'Madrid' },
    { name: 'Sri Lanka', code: 'LK', capital: 'Colombo' },
    { name: 'Sudan', code: 'SD', capital: 'Khartoum' },
    { name: 'Suriname', code: 'SR', capital: 'Paramaribo' },
    { name: 'Huippuvuoret ja Jan Mayen', code: 'SJ', capital: 'Longyearbyen' },
    { name: 'Swazimaa', code: 'SZ', capital: 'Mbabane' },
    { name: 'Ruotsi', code: 'SE', capital: 'Stockholm' },
    { name: 'Sveitsi', code: 'CH', capital: 'Berne' },
    { name: 'Syyria', code: 'SY', capital: 'Damascus' },
    { name: 'Taiwan, Kiinan maakunta', code: 'TW', capital: 'Taipei' },
    { name: 'Tadžikistan', code: 'TJ', capital: 'Dushanbe' },
    { name: 'Tansania, Tanskan tasavalta', code: 'TZ', capital: 'Dodoma' },
    { name: 'Thaimaa', code: 'TH', capital: 'Bangkok' },
    { name: 'Itä-Timor', code: 'TL', capital: 'Dili' },
    { name: 'Mennä', code: 'TG', capital: 'Lome' },
    { name: 'Tokelau', code: 'TK', capital: '' },
    { name: 'Tonga', code: 'TO', capital: 'Nuku\'alofa' },
    { name: 'Trinidad ja Tobago', code: 'TT', capital: 'Port of Spain' },
    { name: 'Tunisia', code: 'TN', capital: 'Tunis' },
    { name: 'Turkki', code: 'TR', capital: 'Ankara' },
    { name: 'Turkmenistan', code: 'TM', capital: 'Ashgabat' },
    { name: 'Turks-ja Caicossaaret', code: 'TC', capital: 'Cockburn Town' },
    { name: 'Tuvalu', code: 'TV', capital: 'Funafuti' },
    { name: 'Uganda', code: 'UG', capital: 'Kampala' },
    { name: 'Ukraina', code: 'UA', capital: 'Kiev' },
    { name: 'Yhdistyneet Arabiemiirikunnat', code: 'AE', capital: 'Abu Dhabi' },
    { name: 'Yhdistynyt kuningaskunta', code: 'GB', capital: 'London' },
    { name: 'Yhdysvallat', code: 'US', capital: 'Washington' },
    { name: 'Yhdysvaltojen pienet syrjäiset saaret', code: 'UM', capital: '' },
    { name: 'Uruguay', code: 'UY', capital: 'Montevideo' },
    { name: 'Uzbekistan', code: 'UZ', capital: 'Tashkent' },
    { name: 'Vanuatu', code: 'VU', capital: 'Port Vila' },
    { name: 'Venezuela', code: 'VE', capital: 'Caracas' },
    { name: 'Vietnam', code: 'VN', capital: 'Hanoi' },
    { name: 'Neitsytsaaret, Brittiläinen', code: 'VG', capital: 'Road Town' },
    { name: 'Neitsytsaaret, Yhdysvallat', code: 'VI', capital: 'Charlotte Amalie' },
    { name: 'Wallis ja Futuna', code: 'WF', capital: 'Mata Utu' },
    { name: 'Länsi-Sahara', code: 'EH', capital: 'El-Aaiun' },
    { name: 'Jemen', code: 'YE', capital: 'Sanaa' },
    { name: 'Sambia', code: 'ZM', capital: 'Lusaka' },
    { name: 'Zimbabwe', code: 'ZW', capital: 'Harare' }
];