import { colorFormat, zipCodeFormat } from '../interfaces';

export const DEFAULT_ARRAY_LENGTH: number = 10;
export const GAP_YEARS: number = 20;
export const FORMAT_DATE: string = 'dd/MM/yyyy';
export const FORMAT_DATE_TIME: string = 'yyyy-MM-dd\'T\'HH:mm:ss.SSSXXX';
export const FORMAT_TIME: string = 'HH:mm:ss';
export const MINIMUM_NUMBER: number = -10000;
export const MAXIMUM_NUMBER: number = 10000;
export const MINIMUM_WORD: number = 10;
export const MAXIMUM_WORD: number = 30;
export const DEFAULT_ZIP_CODE_FORMAT: zipCodeFormat = 'any';
export const DEFAULT_COLOR_FORMAT: colorFormat = 'name';
export const REGEX_VENDORS = {
    masterCard: '^5[1-5][0-9]{14}$',
    visa: '^4[0-9]{12}(?:[0-9]{3})?$',
    americanExpress: '^3[47][0-9]{13}$',
    discoverCard: '^6(?:011|5[0-9]{2})[0-9]{12}$'
};
export const FIRST_NAMES = [ 'John', 'Jane', 'Michael', 'Emily', 'David', 'Sarah', 'Daniel', 'Olivia', 'James', 'Emma',
    'Ava', 'Matthew', 'William', 'Sophia', 'Joseph', 'Isabella', 'Benjamin', 'Mia', 'Jacob', 'Charlotte', 'Samuel', 'Amelia',
    'Henry', 'Evelyn', 'Lucas', 'Mohammed', 'Jackson', 'Ali', 'Sebastian', 'Jayden', 'Elizabeth', 'Ethan', 'Mila', 'Alexander',
    'Ella', 'Joshua', 'Grace', 'Aria', 'Julian', 'Chloe', 'Vincent', 'Aubrey', 'Dylan', 'Zoe', 'Grayson', 'Levi', 'Isaac',
    'Hannah', 'Julia', 'Nathan', 'Lily', 'Theodore', 'Amelia', 'Caleb', 'Mason', 'Eli', 'Adam', 'Aiden', 'Ryan', 'Carter',
    'Wyatt', 'Ezra', 'Natalie', 'Jaxon', 'Hudson', 'Luke', 'Landon', 'Nolan', 'Aaron', 'Cameron'
];
export const LAST_NAMES = [ 'Smith', 'Johnson', 'Williams', 'Brown', 'Taylor', 'Anderson', 'Jones', 'Miller', 'Davis',
    'Garcia', 'Rodriguez', 'Martinez', 'Hernandez', 'Lopez', 'Gonzalez', 'Wilson', 'Anderson', 'Thomas', 'Lee', 'Walker',
    'Hall', 'Allen', 'Young', 'Harris', 'King', 'Wright', 'Hill', 'Scott', 'Green', 'Adams', 'Baker', 'Nelson', 'Carter',
    'Mitchell', 'Perez', 'Roberts', 'Turner', 'Phillips', 'Campbell', 'Parker', 'Evans', 'Edwards', 'Collins', 'Stewart',
    'Sanchez', 'Morris', 'Rogers', 'Reed', 'Cook', 'Morgan', 'Bell', 'Murphy', 'Bailey', 'Rivera', 'Cooper', 'Richardson',
];
export const PROTOCOLS = [ 'http', 'https', 'ftp', 'ftps' ];
export const EMAIL_DOMAINS = [ 'gmail.com', 'gmail.ca', 'yandex.com.ua', 'yandex.com.by', 'yandex.com.kz', 'hotmail.com',
    'yahoo.it', 'yahoo.com', 'icloud.com', 'yandex.by', 'yandex.kz', 'live.com', 'msn.com', 'gmail.de', 'outlook.com',
    'mail.com', 'yahoo.fr', 'inbox.com', 'aol.com', 'zoho.com', 'yahoo.de', 'protonmail.com', 'yandex.ru', 'yandex.com',
    'yandex.ua', 'yandex.com.tr'
];
export const DOMAINS = [ 'google.com', 'facebook.com', 'twitter.com', 'amazon.com', 'youtube.com', 'reddit.com', 'linkedin.com', 'ebay.com',
    'wikipedia.org', 'instagram.com', 'microsoft.com', 'apple.com', 'yahoo.com', 'netflix.com', 'cnn.com', 'wordpress.org', 'adobe.com',
    'github.com', 'nytimes.com', 'stackoverflow.com', 'craigslist.org', 'imdb.com', 'espn.com', 'nasa.gov', 'weather.com', 'pinterest.com',
    'bbc.co.uk', 'nike.com', 'spotify.com', 'nationalgeographic.com', 'forbes.com', 'cnbc.com', 'hulu.com', 'whitehouse.gov', 'npr.org',
    'usnews.com', 'oracle.com', 'nintendo.com', 'cbsnews.com', 'huffpost.com', 'harvard.edu', 'britannica.com' ];

export const STREETS = [ 'Abbey Road', 'Akihabara Electric Town', 'Anna Salai', 'Aspen Street', 'Avenue des Champs-Élysées', 'Avenue Foch',
    'Avenue Montaigne', 'Bay Street', 'Baker Street', 'Berliner Straße', 'Birch Road', 'Bond Street', 'Bourke Street', 'Brigade Road',
    'Boulevard Haussmann', 'Boulevard Saint-Michel', 'Burrard Street', 'Cedar Lane', 'Chestnut Street', 'Chandni Chowk', 'Church Road',
    'Collins Street', 'Cypress Road', 'Dresdner Straße', 'Dotonbori', 'Dundas Street', 'Elm Street', 'Elizabeth Street', 'Flinders Street',
    'Fleet Street', 'Frankfurter Allee', 'Friedrichstraße', 'George Street', 'Ginza', 'Gion', 'Goethestraße', 'Granville Street',
    'Harajuku Takeshita Street', 'Hauptstraße', 'Hickory Court', 'High Street', 'Hill Road', 'Jawaharlal Nehru Road', 'Janpath', 'Juniper Drive',
    'Kaiserstraße', 'King Street', 'King\'s Road', 'Kurfürstendamm', 'La Trobe Street', 'Linking Road', 'Lodi Road', 'Lombard Street',
    'London Road', 'Ludwigstraße', 'Magnolia Street', 'Main Street', 'Maple Drive', 'Marine Drive', 'MG Road', 'Münchner Straße',
    'Nakamise Shopping Street', 'Nihonbashi', 'Oak Avenue', 'Odaiba', 'Omotesando', 'Oxford Street', 'Park Avenue', 'Park Street',
    'Pine Street', 'Pitt Street', 'Place Vendôme', 'Poplar Avenue', 'Portage Avenue', 'Portobello Road', 'Queen Street', 'Redwood Lane',
    'Robson Street', 'Roppongi Hills', 'Rue de la Croix', 'Rue de la Paix', 'Rue de Rivoli', 'Rue des Rosiers', 'Rue du Commerce',
    'Rue du Faubourg Saint-Honoré', 'Rue Saint-Honoré', 'Schlossallee', 'Shibuya Crossing', 'Shinjuku Golden Gai', 'Smith Street',
    'Spencer Street', 'Spruce Avenue', 'St. Catherine Street', 'Station Road', 'Sassafras Drive', 'Savile Row', 'Smith Street', 'Sycamore Lane',
    'Swanston Street', 'Walnut Lane', 'Whyte Avenue', 'Willow Lane', 'Wilhelmstraße', 'Yonge Street'
];

export const COLORS = [ 'Red', 'Orange', 'Yellow', 'Green', 'Blue', 'Indigo', 'Violet', 'Black', 'White', 'Gray', 'Brown', 'Pink', 'Purple',
    'Cyan', 'Magenta', 'Lavender', 'Teal', 'Turquoise', 'Maroon', 'Navy', 'Gold', 'Silver', 'Coral', 'Lime', 'Olive', 'Plum', 'Salmon', 'Slate',
    'Tan', 'Wheat', 'Aquamarine', 'Beige', 'Crimson', 'Ivory', 'Khaki', 'Lemon', 'Mint', 'Periwinkle', 'Rose', 'Saffron', 'Sky', 'Tomato',
    'Amber', 'Bisque', 'Chartreuse', 'Chocolate', 'Fuchsia', 'Lavender', 'Mauve', 'Ochre', 'Peach', 'Pear', 'Ruby', 'Sapphire', 'Tangerine',
    'Topaz', 'Cerulean', 'Denim', 'Emerald', 'Magenta', 'Mulberry', 'Onyx', 'Platinum', 'Rust', 'Sage', 'Sepia', 'Terra', 'Verdigris',
    'Vermilion', 'Viridian', 'Zaffre', 'Alizarin', 'Amaranth', 'Auburn', 'Bittersweet', 'Burgundy', 'Byzantium', 'Carmine', 'Cordovan',
    'Crimson', 'Dandelion', 'Ebony', 'Firebrick', 'Flamingo', 'Gamboge', 'Harlequin', 'Heliotrope', 'Honeydew', 'Isabelline', 'Jade', 'Jonquil',
    'Lilac', 'Marigold', 'Moccasin', 'Mustard', 'Ocean', 'Pansy', 'Papaya', 'Peach', 'Pearly', 'Pine', 'Razzmatazz', 'Robin', 'Sapphire',
    'Seashell', 'Sunset', 'Thistle', 'Tickle', 'Tumbleweed', 'Ultramarine', 'Vanilla', 'Violet', 'Watermelon', 'Wild', 'Zinnwaldite',
    'Amethyst', 'Burgundy', 'Cobalt', 'Cyan', 'Emerald', 'Gold', 'Jade', 'Lilac', 'Magenta', 'Ruby', 'Sapphire', 'Silver', 'Turquoise', 'Violet'
];

export const ANIMALS = [ 'cat', 'dog', 'elephant', 'lion', 'tiger', 'giraffe', 'zebra', 'monkey', 'bear', 'horse', 'penguin', 'koala', 'dolphin',
    'panda', 'cheetah', 'snake', 'crocodile', 'rhinoceros', 'hippopotamus', 'gorilla', 'parrot', 'camel', 'otter', 'rabbit', 'chimpanzee',
    'gazelle', 'seahorse', 'octopus', 'jaguar', 'polar bear', 'flamingo', 'elephant seal', 'zebu', 'scorpion', 'peacock', 'kangaroo', 'wombat',
    'orca', 'quokka', 'platypus', 'lemur', 'alpaca', 'hammerhead shark', 'hedgehog', 'sloth', 'wolf', 'raccoon', 'armadillo', 'chinchilla',
    'goat', 'bison', 'lynx', 'emu', 'puffin', 'walrus', 'beaver', 'meerkat', 'hyena', 'pangolin', 'yak', 'mongoose', 'koala', 'ibex', 'buffalo',
    'lynx', 'porcupine', 'warthog', 'quail', 'elephant bird', 'tapir', 'narwhal', 'cockatoo', 'lemming', 'squirrel', 'rattlesnake', 'panther',
    'wolverine', 'toucan', 'zebadiah', 'cow', 'sheep', 'goose', 'duck', 'pig', 'chicken', 'turkey', 'donkey', 'deer', 'goat', 'rabbit', 'mouse',
    'rat', 'guinea pig', 'hamster', 'ferret', 'llama', 'alpaca', 'yak', 'reindeer', 'buffalo', 'bison', 'moose', 'elk', 'zebu', 'giraffe',
    'hippopotamus', 'pangolin', 'anteater', 'beagle', 'cockroach', 'dalmatian', 'echidna', 'falcon', 'goldfish', 'honey badger', 'iguana',
    'jellyfish', 'koala bear', 'lemur', 'mongoose', 'newt', 'opossum', 'penguin', 'quokka', 'raccoon', 'salamander', 'toucan', 'umbrellabird',
    'vampire bat', 'walrus', 'x-ray tetra', 'yak', 'zebra', 'aardvark', 'butterfly', 'caterpillar', 'dragonfly', 'elephant seal', 'firefly',
    'grasshopper', 'honeybee', 'inchworm', 'jellyfish', 'katydid'
];

export const CURRENCIES = {
    'AFA': '؋',
    'ALL': 'Lek',
    'DZD': 'دج',
    'AOA': 'Kz',
    'ARS': '$',
    'AMD': '֏',
    'AWG': 'ƒ',
    'AUD': '$',
    'AZN': 'm',
    'BSD': 'B$',
    'BHD': '.د.ب',
    'BDT': '৳',
    'BBD': 'Bds$',
    'BYR': 'Br',
    'BEF': 'fr',
    'BZD': '$',
    'BMD': '$',
    'BTN': 'Nu.',
    'BTC': '฿',
    'BOB': 'Bs.',
    'BAM': 'KM',
    'BWP': 'P',
    'BRL': 'R$',
    'GBP': '£',
    'BND': 'B$',
    'BGN': 'Лв.',
    'BIF': 'FBu',
    'KHR': 'KHR',
    'CAD': '$',
    'CVE': '$',
    'KYD': '$',
    'XOF': 'CFA',
    'XAF': 'FCFA',
    'XPF': '₣',
    'CLP': '$',
    'CLF': 'CLF',
    'CNY': '¥',
    'COP': '$',
    'KMF': 'CF',
    'CDF': 'FC',
    'CRC': '₡',
    'HRK': 'kn',
    'CUC': '$, CUC',
    'CZK': 'Kč',
    'DKK': 'Kr.',
    'DJF': 'Fdj',
    'DOP': '$',
    'XCD': '$',
    'EGP': 'ج.م',
    'ERN': 'Nfk',
    'EEK': 'kr',
    'ETB': 'Nkf',
    'EUR': '€',
    'FKP': '£',
    'FJD': 'FJ$',
    'GMD': 'D',
    'GEL': 'ლ',
    'DEM': 'DM',
    'GHS': 'GH₵',
    'GIP': '£',
    'GRD': '₯, Δρχ, Δρ',
    'GTQ': 'Q',
    'GNF': 'FG',
    'GYD': '$',
    'HTG': 'G',
    'HNL': 'L',
    'HKD': '$',
    'HUF': 'Ft',
    'ISK': 'kr',
    'INR': '₹',
    'IDR': 'Rp',
    'IRR': '﷼',
    'IQD': 'د.ع',
    'ILS': '₪',
    'ITL': 'L,£',
    'JMD': 'J$',
    'JPY': '¥',
    'JOD': 'ا.د',
    'KZT': 'лв',
    'KES': 'KSh',
    'KWD': 'ك.د',
    'KGS': 'лв',
    'LAK': '₭',
    'LVL': 'Ls',
    'LBP': '£',
    'LSL': 'L',
    'LRD': '$',
    'LYD': 'د.ل',
    'LTC': 'Ł',
    'LTL': 'Lt',
    'MOP': '$',
    'MKD': 'ден',
    'MGA': 'Ar',
    'MWK': 'MK',
    'MYR': 'RM',
    'MVR': 'Rf',
    'MRO': 'MRU',
    'MUR': '₨',
    'MXN': '$',
    'MDL': 'L',
    'MNT': '₮',
    'MAD': 'MAD',
    'MZM': 'MT',
    'MMK': 'K',
    'NAD': '$',
    'NPR': '₨',
    'ANG': 'ƒ',
    'TWD': '$',
    'NZD': '$',
    'NIO': 'C$',
    'NGN': '₦',
    'KPW': '₩',
    'NOK': 'kr',
    'OMR': '.ع.ر',
    'PKR': '₨',
    'PAB': 'B/.',
    'PGK': 'K',
    'PYG': '₲',
    'PEN': 'S/.',
    'PHP': '₱',
    'PLN': 'zł',
    'QAR': 'ق.ر',
    'RON': 'lei',
    'RUB': '₽',
    'RWF': 'FRw',
    'SVC': '₡',
    'WST': 'SAT',
    'STD': 'Db',
    'SAR': '﷼',
    'RSD': 'din',
    'SCR': 'SRe',
    'SLL': 'Le',
    'SGD': '$',
    'SKK': 'Sk',
    'SBD': 'Si$',
    'SOS': 'Sh.so.',
    'ZAR': 'R',
    'KRW': '₩',
    'SSP': '£',
    'XDR': 'SDR',
    'LKR': 'Rs',
    'SHP': '£',
    'SDG': '.س.ج',
    'SRD': '$',
    'SZL': 'E',
    'SEK': 'kr',
    'CHF': 'CHf',
    'SYP': 'LS',
    'TJS': 'SM',
    'TZS': 'TSh',
    'THB': '฿',
    'TOP': '$',
    'TTD': '$',
    'TND': 'ت.د',
    'TRY': '₺',
    'TMT': 'T',
    'UGX': 'USh',
    'UAH': '₴',
    'AED': 'إ.د',
    'UYU': '$',
    'USD': '$',
    'UZS': 'лв',
    'VUV': 'VT',
    'VEF': 'Bs',
    'VND': '₫',
    'YER': '﷼',
    'ZMK': 'ZK',
    'ZWL': '$'
};